# Generated by Django 3.0.8 on 2020-07-13 20:11

from django.db import migrations, models
import django.db.models.deletion
import qrback.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('has_unique_tables', models.BooleanField(default=False)),
                ('has_unique_categories', models.BooleanField(default=False)),
                ('count_of_max_table', models.IntegerField(default=50)),
                ('extra_fee', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('menu', models.ImageField(blank=True, null=True, upload_to=qrback.models.get_image_path)),
                ('slug', models.SlugField()),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrback.AccountType')),
                ('categories', models.ManyToManyField(to='qrback.Category')),
            ],
        ),
    ]
