# Generated by Django 3.0.8 on 2020-08-04 18:32

from django.db import migrations, models
import django.db.models.deletion
import qrback.models


class Migration(migrations.Migration):

    dependencies = [
        ('qrback', '0001_initial'),
    ]

    operations = [
    ]
