# Generated by Django 3.0.8 on 2020-08-04 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrback', '0002_auto_20200804_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='has_digital_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='facebook',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='instagram',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='company',
            name='tripadvisor',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='twitter',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
