# Generated by Django 3.0.8 on 2020-08-04 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrback', '0003_auto_20200804_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttype',
            name='has_digital_menu',
        ),
        migrations.RemoveField(
            model_name='company',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='company',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tripadvisor',
        ),
        migrations.RemoveField(
            model_name='company',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='category',
        ),
        migrations.AddField(
            model_name='entry',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qrback.FoodCategory'),
            preserve_default=False,
        ),
    ]
