# Generated by Django 3.0.8 on 2020-08-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrback', '0004_auto_20200804_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='detail',
            field=models.CharField(default='item detail', max_length=100),
            preserve_default=False,
        ),
    ]
