# Generated by Django 3.0.8 on 2020-08-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrback', '0012_auto_20200805_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_entry',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
