# Generated by Django 3.0.8 on 2020-08-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrback', '0016_auto_20200807_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account_entry',
            old_name='is_paid',
            new_name='is_delivered',
        ),
    ]
