# Generated by Django 3.0.8 on 2020-08-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrback', '0017_auto_20200807_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_entry',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
