# Generated by Django 3.0.8 on 2020-08-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrback', '0020_auto_20200809_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='requesting_garson',
            field=models.BooleanField(default=False),
        ),
    ]
