# Generated by Django 3.0.8 on 2020-08-20 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import qrback.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qrback', '0021_accounting_requesting_garson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Menü Ürünü', 'verbose_name_plural': 'Menü Ürünleri'},
        ),
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': 'Menü Kategorisi', 'verbose_name_plural': 'Menü Kategorileri'},
        ),
        migrations.AlterModelOptions(
            name='foodgroup',
            options={'verbose_name': 'Menü Grubu', 'verbose_name_plural': 'Menü Grupları'},
        ),
        migrations.AddField(
            model_name='company',
            name='menu_background',
            field=models.ImageField(blank=True, help_text='Bu kısım sadece dijital menü kullanan kullanıcılarımıza özeldir', null=True, upload_to=qrback.models.get_image_path),
        ),
        migrations.AddField(
            model_name='company',
            name='not_order_background',
            field=models.ImageField(blank=True, help_text='Bu kısım sadece siparişsiz dijital menü kullanan kullanıcılarımıza özeldir', null=True, upload_to=qrback.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='company',
            name='menu',
            field=models.ImageField(blank=True, help_text='Bu kısım resim bazlı menü kullanan kullanıcılarımıza özeldir', null=True, upload_to=qrback.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrback.FoodCategory', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_entry', to='qrback.Company', verbose_name='sirket'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='detail',
            field=models.CharField(max_length=100, verbose_name='ürün detayı'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=qrback.models.get_image_path, verbose_name='kapak fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(max_length=30, verbose_name='isim'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='price',
            field=models.FloatField(verbose_name='fiyat'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qrback.FoodGroup', verbose_name='grup'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=qrback.models.get_image_path, verbose_name='kapak fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.CharField(max_length=20, verbose_name='isim'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='sahip'),
        ),
        migrations.AlterField(
            model_name='foodgroup',
            name='name',
            field=models.CharField(max_length=20, verbose_name='isim'),
        ),
        migrations.AlterField(
            model_name='foodgroup',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='sahip'),
        ),
    ]
