# Generated by Django 3.0.8 on 2020-08-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrback', '0022_auto_20200820_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='pinterest',
            new_name='whatsapp',
        ),
    ]
