# Generated by Django 3.0.8 on 2020-08-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrback', '0024_auto_20200821_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
