# Generated by Django 3.0.8 on 2020-08-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrback', '0025_company_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slogan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
