# Generated by Django 3.0.8 on 2020-08-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrback', '0027_auto_20200822_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hide_on_referances',
            field=models.BooleanField(default=False, help_text='Referanslarimiz içerisinde gözükmek istemiyorsanız bu kutucuğu işaretleyerek bunu belirtebilirsiniz.'),
        ),
    ]
