# Generated by Django 3.0.8 on 2020-09-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrback', '0029_auto_20200829_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='is_abstract',
            field=models.BooleanField(default=False,
                                      help_text='Aktifleştirildiğinde bu kategoride bulunan ürünlerin fiyatları müşterilere gösterilmez.(sadece dijital siparişli menü içindir)',
                                      verbose_name='soyut'),
        ),
    ]
