# Generated by Django 3.0.8 on 2020-09-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrback', '0030_auto_20200906_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='prefix',
            field=models.SlugField(default='menu', verbose_name='prefix'),
        ),
    ]
