# Generated by Django 3.0.8 on 2020-09-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrback', '0031_company_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hepsiburada',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='n11',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='trendyol',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='websitesi',
            field=models.URLField(blank=True),
        ),
    ]
