# Generated by Django 3.0.8 on 2020-10-05 11:11

from django.db import migrations
import image_optimizer.fields
import qrback.models


class Migration(migrations.Migration):

    dependencies = [
        ('qrback', '0032_auto_20200921_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='hepsiburada',
        ),
        migrations.RemoveField(
            model_name='company',
            name='n11',
        ),
        migrations.RemoveField(
            model_name='company',
            name='trendyol',
        ),
        migrations.RemoveField(
            model_name='company',
            name='websitesi',
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to=qrback.models.get_image_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='menu_background',
            field=image_optimizer.fields.OptimizedImageField(blank=True, help_text='Bu kısım sadece dijital menü kullanan kullanıcılarımıza özeldir', null=True, upload_to=qrback.models.get_image_path, verbose_name='dijital menü banner'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to=qrback.models.get_image_path, verbose_name='kapak fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to=qrback.models.get_image_path, verbose_name='kapak fotoğrafı'),
        ),
    ]
