# Generated by Django 3.0.8 on 2020-10-14 22:06

from django.db import migrations, models
import qrback.models


class Migration(migrations.Migration):

    dependencies = [
        ('qrback', '0033_auto_20201005_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_192',
            field=models.ImageField(blank=True, null=True, upload_to=qrback.models.get_image_path, verbose_name='192x logo'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_512',
            field=models.ImageField(blank=True, null=True, upload_to=qrback.models.get_image_path, verbose_name='512x logo'),
        ),
    ]
