# Generated by Django 3.0.8 on 2020-10-14 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrback', '0034_auto_20201015_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='logo_192',
            new_name='logo_96',
        ),
    ]
