# Generated by Django 3.0.8 on 2020-11-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrback', '0035_auto_20201015_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='has_whatsapp_order',
            field=models.BooleanField(default=False),
        ),
    ]
