# Generated by Django 3.0.8 on 2020-11-04 21:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qrback', '0036_accounttype_has_whatsapp_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 21, 41, 18, 319466, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiflik Durumu'),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
