# Generated by Django 3.0.8 on 2020-11-04 21:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qrback', '0037_auto_20201105_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='payment_date',
        ),
        migrations.AlterField(
            model_name='company',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 21, 46, 45, 338872, tzinfo=utc)),
        ),
    ]
