# Generated by Django 3.0.8 on 2021-03-11 16:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import qrback.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qrback', '0040_auto_20210311_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 16, 36, 49, 558907, tzinfo=utc), verbose_name='Lisans bitiş tarihi'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('document', models.FileField(upload_to=qrback.models.get_pdf_path)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_doc', to='qrback.Company', verbose_name='sirket')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='sahip')),
            ],
        ),
    ]
